spring.application.name=product-api
server.port=9091

# Database
spring.datasource.url=jdbc:mysql://localhost:3307/wso2_is_product_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=QW123Chathura
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# WSO2 Identity Server Issuer URL
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://65.2.92.126:9443/oauth2/token

# Self-signed certificate errors
server.ssl.enabled=false

logging.level.org.springframework.security=DEBUG
